theme: jekyll-theme-cayman
url: CookieMonster1819.github.io
title: Welcome to Taylor Doyka's homepage !
description: Feel welcome to bookmark this page, for it is my ePotfolio completed within my CS-499 Computer Science Capstone !
